created referral v2 page
KyberNetwork/kyberswap-interface pull request #1037
Opened 2022-06-20 02:42 UTC by XiaoYhun

2022-07-19 20:19 UTC, viet-nv requested changes

2022-07-19 20:19 UTC, viet-nv commented on src/pages/ReferralV2/CopyHelper.tsx
> +export default function CopyHelper({ textToCopy }: { textToCopy: string }) {
we already have `CopyHelper`
Please re-use component, If design use different copy icon, just raise with designer that we need a consistent copy icon

2022-07-19 20:19 UTC, viet-nv commented on src/pages/ReferralV2/Leaderboard.tsx
> +const Pagination = ({
Dung is already create a Pagination component, can you re-use it?

2022-07-19 20:19 UTC, viet-nv commented on src/pages/ReferralV2/Leaderboard.tsx
> +            onSearch={value => {
you can use onSearch={setSearchValue}

2022-07-19 20:19 UTC, viet-nv commented on src/pages/ReferralV2/ShareLinkModal.tsx
> +  color: #222;
why these colors are hardcoded?

2022-07-19 20:19 UTC, viet-nv commented on src/pages/ReferralV2/TimerCountdown.tsx
> +  }, [startTime])
also `durationInSeconds`

2022-07-19 20:19 UTC, viet-nv commented on src/pages/ReferralV2/index.tsx
> +import useMixpanel, { MIXPANEL_TYPE } from 'hooks/useMixpanel'
add a blank line to separate import section

2022-07-19 20:19 UTC, viet-nv commented on src/pages/ReferralV2/index.tsx
> +  }, [account])
did you check dependencies for this effect?

2022-07-19 20:19 UTC, viet-nv commented on src/theme/styled.d.ts
> +  stroke: Color
change border color, dont need a new color variable

2022-07-20 01:17 UTC, XiaoYhun commented on src/hooks/useReferralV2.ts
> +        body: JSON.stringify({ wallet: account, chainId: '4', ref: '', clientCode: 'referral' }),
sure, I'm usually only recheck everything after testing done, so many hardcode, test code remaining at the moment.

2022-07-20 01:25 UTC, XiaoYhun commented on src/pages/App.tsx
> +                    <Route exact path="/refer" component={ReferralV2} />
I think because we dont want the v2 in url, already have referral page existed

2022-07-20 01:28 UTC, XiaoYhun commented on src/hooks/useReferralV2.ts
> +        body: JSON.stringify({ wallet: account, chainId: '4', ref: '', clientCode: 'referral' }),
I think better you should let PR owner annouce review required first, it will less work for you I think, also less communication needed.

2022-07-20 02:00 UTC, viet-nv commented on src/hooks/useReferralV2.ts
> +        body: JSON.stringify({ wallet: account, chainId: '4', ref: '', clientCode: 'referral' }),
If PR is not ready, you can create a draft PR. 
Yesterday QA announce that referral is ready for release, that why I review this PR. 
an other reason that if we do a standard process, PR should be reviewed before testing by QA :D

2022-07-20 02:05 UTC, viet-nv commented on src/pages/App.tsx
> +                    <Route exact path="/refer" component={ReferralV2} />
V1 is deprecated right?
I dont see any way to enter that page. Should remove it

2022-07-20 02:50 UTC, XiaoYhun commented on src/hooks/useReferralV2.ts
> +        body: JSON.stringify({ wallet: account, chainId: '4', ref: '', clientCode: 'referral' }),
yeah, but how if QA asked to add something or bug fixing, we need to review it again?, anyway better I will create draft PR from now on :D

2022-07-27 07:14 UTC, viet-nv requested changes

2022-07-27 07:14 UTC, viet-nv commented on .env.production
> +REACT_APP_AGGREGATOR_API=https://aggregator-api.stg.kyberengineering.io
noted Need to change when merging

2022-07-27 07:14 UTC, viet-nv commented on .env.stg
> +REACT_APP_AGGREGATOR_API=https://aggregator-api.dev.kyberengineering.io
please revert to stg

2022-07-27 07:14 UTC, viet-nv commented on .env.stg
> +REACT_APP_REWARD_SERVICE_API=https://reward.dev.kyberengineering.io/api/v1
revert to stg api

2022-07-27 07:14 UTC, viet-nv commented on src/pages/ReferralV2/Leaderboard.tsx
> +//     height: 36px;
remove this code if we dont need it

2023-07-14 10:31 UTC, closed without merging