feat: improve slippage setting
KyberNetwork/kyberswap-interface pull request #1275
Opened 2022-08-22 02:57 UTC by TienPQ149

2022-08-22 03:01 UTC, hungdoansy commented on src/pages/SwapV2/index.tsx
> +  const isStableSwap =
I'd suggest this should be changed to `isStableCoinSwap`

2022-08-22 03:01 UTC, hungdoansy submitted a review, later dismissed
LGTM

2022-08-22 03:02 UTC, viet-nv requested changes

2022-08-22 03:02 UTC, viet-nv commented on src/pages/SwapV2/index.tsx
> +    }
wrong business logic here

2022-08-22 03:02 UTC, nguyenhoaidanh commented on src/pages/SwapV2/index.tsx
> +    INPUT.currencyId &&
INPUT?.currencyId

2022-08-25 07:46 UTC, viet-nv approved these changes

2022-08-25 07:50 UTC, nguyenhoaidanh approved these changes

2022-08-25 07:51 UTC, merged