Crosschain swap
KyberNetwork/kyberswap-interface pull request #1881
Opened 2023-04-17 02:24 UTC by nguyenhoaidanh

2023-05-16 07:35 UTC, nhd98z requested changes

2023-05-16 16:02 UTC, nguyenhoaidanh commented on src/components/Announcement/Popups/TransactionPopup.tsx
> +  [TRANSACTION_TYPE.BRIDGE]: summaryCrossChain,
same noti.
bridge and cross-chain swap are both called `cross-chain`. summaryCrossChain would be fined, I think.

2023-05-16 16:05 UTC, nguyenhoaidanh commented on src/components/Announcement/index.tsx
> +        resetUnread(RTK_QUERY_TAGS.GET_TOTAL_UNREAD_PRIVATE_ANN)
there are 2 ways to invalidate cache rtk query
- 1 . use [invalidatesTags](https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#:~:text=The-,invalidatesTags,-property%20on%20a)
- 2 . dispatch action to invalidate cache
the above is the second one.

2023-05-16 16:23 UTC, nguyenhoaidanh commented on src/components/swapv2/LimitOrder/helpers.ts
> +export const removeTrailingZero = (num: string) => {
good point, I forgot regex can do it better.
your regex don't pass the case: 10.00, 10. 
I will choose this one `str.replace(/^([\d,]+)$|^([\d,]+)\.0*$|^([\d,]+\.[0-9]*?)0*$/, "$1$2$3")`

2023-05-17 08:04 UTC, hungdoansy commented on vite.config.ts
> +  },
By the way, please add `--open` to open the browser when starting (Ref: https://vitejs.dev/guide/cli.html#options)

2023-05-17 08:09 UTC, nguyenhoaidanh commented on src/components/swapv2/LimitOrder/helpers.ts
> +export const removeTrailingZero = (num: string) => {
how about this Number('1.234000000000000000000000000001') :v

2023-05-17 08:25 UTC, hungdoansy commented on src/components/swapv2/LimitOrder/helpers.ts
> +export const removeTrailingZero = (num: string) => {
```js
Number('1.2340000000000001') // 1.2340000000000002 
```
Well done js =))

2023-06-08 06:39 UTC, nhd98z commented on src/components/swapv2/LimitOrder/helpers.ts
> +  return num.replace(/^([\d,]+)$|^([\d,]+)\.0*$|^([\d,]+\.[0-9]*?)0*$/, '$1$2$3')
It's better if you explain this regex.

2023-06-08 06:40 UTC, nhd98z submitted a review, later dismissed

2023-06-08 06:49 UTC, nguyenhoaidanh commented on src/components/swapv2/LimitOrder/helpers.ts
> +  return num.replace(/^([\d,]+)$|^([\d,]+)\.0*$|^([\d,]+\.[0-9]*?)0*$/, '$1$2$3')
updated

2023-06-08 10:47 UTC, nhd98z approved these changes

2023-06-08 10:49 UTC, merged